name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests with Karma
        env:
          CHROME_BIN: /usr/bin/google-chrome
          DISPLAY: :99  # Configura la variable de entorno DISPLAY
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb  # Instala el servidor X virtual
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  # Inicia el servidor X virtual
          npm run test
